name: Build-test-deploy

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install NPM
        run: npm install

      - name: Build NPM
        run: npm run build
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo - Test
        uses: actions/checkout@v4

      - name: Use Node.js - Test
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install NPM - Test 
        run: npm install

      - name: Build NPM - Test
        run: npm test        
